
services:

  backend:
    image: kennyloc/backendimage:latest
    ports:
      - "9000:9000"

  frontend:
    image: oliver1703dk/frontendimage:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend

  reverse-proxy-nginx:
    container_name: nginx
    image: nginx:1.26.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
