services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BACKEND_PORT: 9000
      BACKEND_DNS: backend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      REDIS_DNS: database
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: redis:7.4
    volumes:
      - ./redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge