apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: oliver1703dk/backendimagev2:latest
        envFrom:
          - configMapRef:
              name: configbackend
        ports: 
        - containerPort: 9000