apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: oliver1703dk/frontendimagev2:latest
        envFrom:
          - configMapRef:
              name: configfrontend
        ports:
        - containerPort: 8080