apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-fortune-cookie
  labels:
    app: simple-fortune-cookie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-fortune-cookie
  template:
    metadata:
      labels:
        app: simple-fortune-cookie
    spec:
      containers:
      - name: devopsacademyc
        image: eficodeacademy/devopsacademyc:latest
       

