name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.17' # You can specify your desired Go version


    - name: Install dependencies for backend
      working-directory: ./backend
      run: go mod tidy

    - name: Build the project backend 
      working-directory: ./backend
      run: go build  

    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: go mod tidy

    - name: Build the project frontend
      working-directory: ./frontend
      run: go build 


    - name: Run tests 
      working-directory: ./frontend
      run: go test ./...

