name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.17' # You can specify your desired Go version


    - name: Build the project backend 
      run: go build /backend/ 

    - name: Build the project frontend
      run: go build /frontend/
