name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.17' # You can specify your desired Go version

    - name: Install dependencies for backend
      working-directory: ./backend
      run: go mod tidy

    - name: Build the project backend 
      working-directory: ./backend
      run: go build  

    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: go mod tidy

    - name: Build the project frontend
      working-directory: ./frontend
      run: go build 

  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: '^1.17'
        
    - name: Run tests for frontend
      working-directory: ./frontend
      run: go test ./...


  #Linting: 
    #runs-on: ubuntu-latest
    #needs: [Build]
    #steps: 
    #- name: Run linting 
      #run: 
