name: non-main
on:
  push:
    branches:
      - '*'  
    branches-ignore:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.17' 

    - name: Install dependencies for backend
      working-directory: ./backend
      run: go mod tidy

    - name: Build the project backend 
      working-directory: ./backend
      run: go build  

    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: go mod tidy

    - name: Build the project frontend
      working-directory: ./frontend
      run: go build 



  Linting: 
    runs-on: ubuntu-latest
    needs: [Build]
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: '^1.17'

    - name: run linting
      uses: super-linter/super-linter/slim@v5 
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISABLE_ERRORS: true 



